// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApprovePlan(arg1:string):Promise<void>;

export function CreateDirectory(arg1:string,arg2:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function CreateNewProject(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function DeletePath(arg1:string,arg2:string):Promise<void>;

export function GetActiveFiles(arg1:Array<main.ChatMessage>):Promise<Array<string>>;

export function GetDirectoryTree(arg1:string):Promise<main.FileNode>;

export function GetFileContent(arg1:string,arg2:string):Promise<string>;

export function GetProjectSettings(arg1:string):Promise<main.ProjectSettings>;

export function GetProjectSourceString(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsPathIgnored(arg1:string,arg2:string):Promise<boolean>;

export function LoadSettings():Promise<main.AppSettings>;

export function OpenBrowserURL(arg1:string):Promise<void>;

export function OpenPathInExplorer(arg1:string,arg2:string):Promise<void>;

export function RejectPlan(arg1:string,arg2:string):Promise<void>;

export function RenamePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunProject(arg1:string,arg2:string):Promise<void>;

export function SaveFileContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveProjectSettings(arg1:string,arg2:main.ProjectSettings):Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SelectWorkspace():Promise<string>;

export function SendChatMessage(arg1:string,arg2:string,arg3:Array<main.ChatMessage>,arg4:string):Promise<string>;

export function StartAgent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<main.ChatMessage>):Promise<void>;

export function StopAgent(arg1:string):Promise<void>;

export function StopProject(arg1:string):Promise<void>;
