// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApprovePlan(arg1) {
  return window['go']['main']['App']['ApprovePlan'](arg1);
}

export function CreateDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateDirectory'](arg1, arg2);
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function CreateNewProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNewProject'](arg1, arg2, arg3);
}

export function DeletePath(arg1, arg2) {
  return window['go']['main']['App']['DeletePath'](arg1, arg2);
}

export function GetActiveFiles(arg1) {
  return window['go']['main']['App']['GetActiveFiles'](arg1);
}

export function GetDirectoryTree(arg1) {
  return window['go']['main']['App']['GetDirectoryTree'](arg1);
}

export function GetFileContent(arg1, arg2) {
  return window['go']['main']['App']['GetFileContent'](arg1, arg2);
}

export function GetProjectSettings(arg1) {
  return window['go']['main']['App']['GetProjectSettings'](arg1);
}

export function GetProjectSourceString(arg1) {
  return window['go']['main']['App']['GetProjectSourceString'](arg1);
}

export function GetRepoGraph(arg1) {
  return window['go']['main']['App']['GetRepoGraph'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsPathIgnored(arg1, arg2) {
  return window['go']['main']['App']['IsPathIgnored'](arg1, arg2);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenBrowserURL(arg1) {
  return window['go']['main']['App']['OpenBrowserURL'](arg1);
}

export function OpenPathInExplorer(arg1, arg2) {
  return window['go']['main']['App']['OpenPathInExplorer'](arg1, arg2);
}

export function RejectPlan(arg1, arg2) {
  return window['go']['main']['App']['RejectPlan'](arg1, arg2);
}

export function RenamePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2, arg3);
}

export function RunProject(arg1, arg2) {
  return window['go']['main']['App']['RunProject'](arg1, arg2);
}

export function SaveFileContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2, arg3);
}

export function SaveProjectSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectSettings'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function SendChatMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2, arg3, arg4);
}

export function StartAgent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartAgent'](arg1, arg2, arg3, arg4, arg5);
}

export function StopAgent(arg1) {
  return window['go']['main']['App']['StopAgent'](arg1);
}

export function StopProject(arg1) {
  return window['go']['main']['App']['StopProject'](arg1);
}
